# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, pkgs-unstable, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];
  boot = #let 
    #gpuIDs = [
    #  "10de:2208" # Graphics
    #  "10de:1aef" # Audio
    #];
  #in {
  {
    loader = {
      systemd-boot.enable = true;
      efi.canTouchEfiVariables = true;
    };
    kernelPackages =  pkgs-unstable.linuxKernel.packageAliases.linux_default;
    initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
    initrd.kernelModules = [ "kvm-amd" ];
    kernelModules = [ 
      #"vfio_pci" 
      #"vfio" 
      #"vfio_virqfd" 
      #"vfio_iommu_type1"
      "nvidia" 
      "nvidia_modeset" 
      "nvidia_uvm" 
      "nvidia_drm"
    ];
    #boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
    kernelParams = [
      "amd_iommu=on"
      "nvidia_drm.modeset=1"
      #("vfio-pci.ids=" + lib.concatStringsSep "," gpuIDs)
    ];
    #extraModprobeConfig = "options vfio-pci ids=" + lib.concatStringsSep "," gpuIDs;
    # https://forum.level1techs.com/t/nixos-vfio-pcie-passthrough/130916
    #postBootCommands = ''
    #  DEVS="0000:10:00.0 0000:10:00.1"
    #  for DEV in $DEVS; do
    #    echo "vfio-pci" > /sys/bus/pci/devices/$DEV/driver_override
    #  done
    #  modprobe -i vfio-pci
    #'';
  };

  #virtualisation.spiceUSBRedirection.enable = true;

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/bd523c2a-0217-4a70-ac11-705dea030c85";
      fsType = "ext4";
    };

  fileSystems."/home/fafuja/games" =
    { device = "/dev/disk/by-uuid/1eb80166-1147-46c2-96e6-ffcf869b6d71";
      fsType = "ext4";
    };

  fileSystems."/home/fafuja/bigfiles" =
    { device = "/dev/disk/by-uuid/9242c510-83b4-4652-9dc3-88c2f2fe605a";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/0F14-ECBF";
      fsType = "vfat";
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp34s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
