local calendar_panel = require(... .. ".calendar")
local notif_panel = require(... .. ".notifications")
local volumepanel = require(... .. ".volumepanel")

local awful = require("awful")
awful.screen.connect_for_each_screen(function(s)
	calendar_panel(s)
	notif_panel(s)
	volumepanel(s)
end)
